'use strict';

exports.mkBrowser_ = () => {
    const session = Promise.resolve();

    session.commandList = [];
    session.isW3C = false;
    session.isMobile = false;
    session.options = {
        waitforTimeout: 100500
    };

    session.addCommand = sinon.stub().callsFake((name, command) => {
        session[name] = command;
        sinon.spy(session, name);
    });
    session.overwriteCommand = sinon.stub().callsFake((name, command) => {
        session[name] = command.bind(session, session[name]);
        sinon.spy(session, name);
    });

    session.$ = sinon.stub().named('$').resolves(exports.mkElement_());
    session.$$ = sinon.stub().named('$$').resolves([exports.mkElement_(), exports.mkElement_()]);
    session.getUrl = sinon.stub().named('getUrl').resolves();
    session.execute = sinon.stub().named('execute').resolves();
    session.executeAsync = sinon.stub().named('executeAsync').resolves();
    session.deleteCookies = sinon.stub().named('deleteCookies').resolves();
    session.getCookies = sinon.stub().named('getCookies').resolves();
    session.setCookies = sinon.stub().named('setCookies').resolves();
    session.getContext = sinon.stub().named('getContext').resolves();
    session.getContexts = sinon.stub().named('getContexts').resolves();
    session.switchContext = sinon.stub().named('switchContext').resolves();
    session.getCurrentActivity = sinon.stub().named('getCurrentActivity').resolves();
    session.sendKeyEvent = sinon.stub().named('sendKeyEvent').resolves();
    session.getStrings = sinon.stub().named('getStrings').resolves();
    session.getCurrentActivity = sinon.stub().named('getCurrentActivity').resolves();
    session.hideKeyboard = sinon.stub().named('hideKeyboard').resolves();
    session.touchLongClick = sinon.stub().named('touchLongClick').resolves();
    session.launchApp = sinon.stub().named('launchApp').resolves();
    session.getOrientation = sinon.stub().named('getOrientation').resolves();
    session.setOrientation = sinon.stub().named('setOrientation').resolves();
    session.multiTouchPerform = sinon.stub().named('multiTouchPerform').resolves();
    session.touchPerform = sinon.stub().named('touchPerform').resolves();
    session.rotateDevice = sinon.stub().named('rotateDevice').resolves();
    session.setValueImmediate = sinon.stub().named('setValueImmediate').resolves();
    session.getSettings = sinon.stub().named('getSettings').resolves();
    session.updateSettings = sinon.stub().named('updateSettings').resolves();
    session.touchFlick = sinon.stub().named('touchFlick').resolves();
    session.swipe = sinon.stub().named('swipe').resolves();
    session.toggleEnrollTouchId = sinon.stub().named('toggleEnrollTouchId').resolves();
    session.touchClick = sinon.stub().named('touchClick').resolves();
    session.touchLongClick = sinon.stub().named('touchLongClick').resolves();
    session.touchAction = sinon.stub().named('touchAction').resolves();
    session.getElementSize = sinon.stub().named('getElementSize').resolves();
    session.getElementLocationInView = sinon.stub().named('getElementLocationInView').resolves();
    session.getPageSource = sinon.stub().named('getPageSource').resolves();
    session.performActions = sinon.stub().named('performActions').resolves();
    session.acceptAlert = sinon.stub().named('acceptAlert').resolves();
    session.dismissAlert = sinon.stub().named('dismissAlert').resolves();
    session.getAlertText = sinon.stub().named('getAlertText').resolves();
    session.sendAlertText = sinon.stub().named('sendAlertText').resolves();
    session.getApplicationCacheStatus = sinon.stub().named('getApplicationCacheStatus').resolves();
    session.buttonDown = sinon.stub().named('buttonDown').resolves();
    session.buttonUp = sinon.stub().named('buttonUp').resolves();
    session.getAllCookies = sinon.stub().named('getAllCookies').resolves();
    session.addCookie = sinon.stub().named('addCookie').resolves();
    session.deleteAllCookies = sinon.stub().named('deleteAllCookies').resolves();
    session.deleteCookie = sinon.stub().named('deleteCookie').resolves();
    session.positionDoubleClick = sinon.stub().named('positionDoubleClick').resolves();
    session.getActiveElement = sinon.stub().named('getActiveElement').resolves();
    session.getElementAttribute = sinon.stub().named('getElementAttribute').resolves();
    session.elementClear = sinon.stub().named('elementClear').resolves();
    session.elementClick = sinon.stub().named('elementClick').resolves();
    session.getElementCSSValue = sinon.stub().named('getElementCSSValue').resolves();
    session.isElementDisplayed = sinon.stub().named('isElementDisplayed').resolves();
    session.findElementFromElement = sinon.stub().named('findElementFromElement').resolves();
    session.findElementsFromElement = sinon.stub().named('findElementsFromElement').resolves();
    session.isElementEnabled = sinon.stub().named('isElementEnabled').resolves();
    session.getElementLocation = sinon.stub().named('getElementLocation').resolves();
    session.getElementTagName = sinon.stub().named('getElementTagName').resolves();
    session.getElementProperty = sinon.stub().named('getElementProperty').resolves();
    session.getElementRect = sinon.stub().named('getElementRect').resolves();
    session.takeElementScreenshot = sinon.stub().named('takeElementScreenshot').resolves();
    session.isElementSelected = sinon.stub().named('isElementSelected').resolves();
    session.getElementSize = sinon.stub().named('getElementSize').resolves();
    session.getElementText = sinon.stub().named('getElementText').resolves();
    session.elementSendKeys = sinon.stub().named('elementSendKeys').resolves();
    session.switchToFrame = sinon.stub().named('switchToFrame').resolves();
    session.switchToParentFrame = sinon.stub().named('switchToParentFrame').resolves();
    session.activateIME = sinon.stub().named('activateIME').resolves();
    session.isIMEActivated = sinon.stub().named('isIMEActivated').resolves();
    session.getActiveEngine = sinon.stub().named('getActiveEngine').resolves();
    session.getAvailableEngines = sinon.stub().named('getAvailableEngines').resolves();
    session.deactivateIME = sinon.stub().named('deactivateIME').resolves();
    session.newSession = sinon.stub().named('newSession').resolves();
    session.clearLocalStorage = sinon.stub().named('clearLocalStorage').resolves();
    session.deleteLocalStorageItem = sinon.stub().named('deleteLocalStorageItem').resolves();
    session.getLocalStorage = sinon.stub().named('getLocalStorage').resolves();
    session.getLocalStorageItem = sinon.stub().named('getLocalStorageItem').resolves();
    session.setLocalStorage = sinon.stub().named('setLocalStorage').resolves();
    session.getLocalStorageSize = sinon.stub().named('getLocalStorageSize').resolves();
    session.getGeoLocation = sinon.stub().named('getGeoLocation').resolves();
    session.setGeoLocation = sinon.stub().named('setGeoLocation').resolves();
    session.getLogs = sinon.stub().named('getLogs').resolves();
    session.getLogTypes = sinon.stub().named('getLogTypes').resolves();
    session.moveToElement = sinon.stub().named('moveToElement').resolves();
    session.takeScreenshot = sinon.stub().named('takeScreenshot').resolves();
    session.getSession = sinon.stub().named('getSession').resolves();
    session.getSessions = sinon.stub().named('getSessions').resolves();
    session.deleteSession = sinon.stub().named('deleteSession').resolves();
    session.clearSessionStorage = sinon.stub().named('clearSessionStorage').resolves();
    session.deleteSessionStorageItem = sinon.stub().named('deleteSessionStorageItem').resolves();
    session.getSessionStorage = sinon.stub().named('getSessionStorage').resolves();
    session.getSessionStorageItem = sinon.stub().named('getSessionStorageItem').resolves();
    session.setSessionStorage = sinon.stub().named('setSessionStorage').resolves();
    session.getSessionStorageSize = sinon.stub().named('getSessionStorageSize').resolves();
    session.elementSubmit = sinon.stub().named('elementSubmit').resolves();
    session.getTimeouts = sinon.stub().named('getTimeouts').resolves();
    session.setTimeout = sinon.stub().named('setTimeout').resolves();
    session.setAsyncTimeout = sinon.stub().named('setAsyncTimeout').resolves();
    session.setImplicitTimeout = sinon.stub().named('setImplicitTimeout').resolves();
    session.getTitle = sinon.stub().named('getTitle').resolves();
    session.touchScroll = sinon.stub().named('touchScroll').resolves();
    session.closeWindow = sinon.stub().named('closeWindow').resolves();
    session.switchToWindow = sinon.stub().named('switchToWindow').resolves();
    session.getWindowHandle = sinon.stub().named('getWindowHandle').resolves();
    session.fullscreenWindow = sinon.stub().named('fullscreenWindow').resolves();
    session.maximizeWindow = sinon.stub().named('maximizeWindow').resolves();
    session.getWindowPosition = sinon.stub().named('getWindowPosition').resolves();
    session.setWindowPosition = sinon.stub().named('setWindowPosition').resolves();
    session.getWindowSize = sinon.stub().named('getWindowSize').resolves();
    session.setWindowSize = sinon.stub().named('setWindowSize').resolves();
    session.getWindowHandles = sinon.stub().named('getWindowHandles').resolves();
    session.uploadFile = sinon.stub().named('uploadFile').resolves();
    session.reloadSession = sinon.stub().named('reloadSession').resolves();
    session.saveScreenshot = sinon.stub().named('saveScreenshot').resolves();
    session.waitUntil = sinon.stub().named('waitUntil').resolves();
    session.newWindow = sinon.stub().named('newWindow').resolves();
    session.pressKeyCode = sinon.stub().named('pressKeyCode').resolves();
    session.longPressKeyCode = sinon.stub().named('longPressKeyCode').resolves();

    return session;
};

exports.mkElement_ = (opts = {}) => {
    const element = {};

    element.elementId = element.ELEMENT = opts.id || 'default-element-id';

    element.addValue = sinon.stub().named('addValue').resolves();
    element.clearValue = sinon.stub().named('clearValue').resolves();
    element.click = sinon.stub().named('click').resolves();
    element.doubleClick = sinon.stub().named('doubleClick').resolves();
    element.dragAndDrop = sinon.stub().named('dragAndDrop').resolves();
    element.getSize = sinon.stub().named('getSize').resolves();
    element.moveTo = sinon.stub().named('moveTo').resolves();
    element.scrollIntoView = sinon.stub().named('scrollIntoView').resolves();
    element.selectByAttribute = sinon.stub().named('selectByAttribute').resolves();
    element.selectByIndex = sinon.stub().named('selectByIndex').resolves();
    element.selectByVisibleText = sinon.stub().named('selectByVisibleText').resolves();
    element.setValue = sinon.stub().named('setValue').resolves();
    element.touchAction = sinon.stub().named('touchAction').resolves();
    element.getAttribute = sinon.stub().named('getAttribute').resolves();
    element.getCSSProperty = sinon.stub().named('getCSSProperty').resolves();
    element.getHTML = sinon.stub().named('getHTML').resolves();
    element.getLocation = sinon.stub().named('getLocation').resolves();
    element.getTagName = sinon.stub().named('getTagName').resolves();
    element.getText = sinon.stub().named('getText').resolves();
    element.getValue = sinon.stub().named('getValue').resolves();
    element.isFocused = sinon.stub().named('isFocused').resolves();
    element.isEnabled = sinon.stub().named('isEnabled').resolves();
    element.isExisting = sinon.stub().named('isExisting').resolves();
    element.isSelected = sinon.stub().named('isSelected').resolves();
    element.isDisplayed = sinon.stub().named('isDisplayed').resolves();
    element.isDisplayedInViewport = sinon.stub().named('isDisplayedInViewport').resolves();

    return element;
};
